### ISSUE TITLE
No camera found error

### ISSUE THREAD

**Issue by jonny214** [analogdevicesinc/tof-ros#22]
Hello,

I tried to use ROS driver of ADTF3175D evaluation board. The module could work windows GUI v4.2.0. Ubuntu 20.04LTS, ROS noetic is installed on my PC. SD card image is 4.2.0. ADSD3500 firmware version is 4.3.0.
I installed "Crosby" dependency deb file. And build ROS driver on workspace.

![Screenshot from 2023-07-20 14-31-45](https://github.com/analogdevicesinc/tof-ros/assets/28104003/d8bc23e9-0451-471c-8c6e-7c4d50d1de00)

The error is "No camera found".  
I connected ADTF3175D to PC due to USB. I tried to add permission for "/dev/iio:device*" by using "chmod" command. But, it still continue to see same error...

If you have any advice, it is very helpful to use ADTF3175D with ROS.

![Screenshot from 2023-07-20 14-19-06](https://github.com/analogdevicesinc/tof-ros/assets/28104003/164d9372-adf5-4390-a300-1cba9c86202d)

**Comment by rbudai98** [comment]
Hi! The SDK had slight changes during last days and most probably on your pc the old libraries are installed with the latest ROS package. Could you please download again the libraries and install from scratch: https://swdownloads.analog.com/cse/aditof/tof_deb_pkg/crosby/out_ubuntu20/tof_lib.deb

**Comment by jonny214** [comment]
Hi, Thank you so much!
I tried catkin_make with the latest package. But, CMake has error for permission denied.

![image](https://github.com/analogdevicesinc/tof-ros/assets/28104003/8e4d084b-92ad-4947-966a-2702e62976e8)

I tried to add permission by following command. But, it still has error by catkin_make.

`jun@jun:~/tof_ws$ sudo chown $USER: -R ~/tof_ws/`

**Comment by meetgandhi-eic** [comment]
@jonny214 
Seems like ROS_HOME environment variable is not exported in your current terminal. (See: https://github.com/analogdevicesinc/tof-ros/tree/main#3-usage)
![Screenshot from 2023-07-24 10-41-14](https://github.com/analogdevicesinc/tof-ros/assets/128454398/40fde591-d8ad-4bf0-a341-ad2322009310)

**Comment by meetgandhi-eic** [comment]
@jonny214 
I tried to build the latest version and found the similar issue.
This [line](https://github.com/analogdevicesinc/tof-ros/blob/main/CMakeLists.txt#L65) is causing the issue:
`file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/config DESTINATION ${ROS_HOME}/)` 
Please replace the same with:
`file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/config DESTINATION $ENV{ROS_HOME}/)`
This should fix the build.

**Comment by rbudai98** [comment]
Will update it now, thank you for the suggestion!

**Comment by rbudai98** [comment]
Thank you for the enhancement @meetgandhi-eic !
