### ISSUE TITLE
"Old mode detected on camera" error.

### ISSUE THREAD

**Issue by jonny214** [analogdevicesinc/tof-ros#26]
Hello,

Thank you for supporting catkin_make error. I resolved issue by the latest update.

I tried to use launch file example. Then, it has firmware version error...
Camera SDK is the latest image file which are downloaded version 4.2.0 of Win GUI. ADSD3500 firmware is also latest.

Windows GUI said.
ADSD3500 firmware version 4.3.0.0
SD card image version:microsd-4.2.0-b260ad46.img
kernel version: lf-5.10.72-2.2.0
u-boot version: imx_v2020.04_5.4.70_2.3.0

Can I confirm the supported SDK version and ADSD3500 firmware version for the ROS driver?
If the SDK imge or firmware will update in couple of weeks, I would like to wait the update.

![Screenshot from 2023-07-24 15-32-01](https://github.com/analogdevicesinc/tof-ros/assets/28104003/4540cea2-1703-43e9-a941-8ce0aa9c76cc)

Thanks again.
Jun

**Comment by rbudai98** [comment]
Hi! 
The error is caused by the older firmware version that exists on your camera.

**Comment by jonny214** [comment]
Hello,

Thank you so much for your comment.
Which version is required for SDK and ADSD3500 firmware?

Thanks, 
Jun

**Comment by dNechita** [comment]
Hi Jun,

Your firmware is quite new. But your camera is configured to work with old modes ("mp", "qmp") as opposed to new modes ("lr-native", "sr-native", "lr-qnative", "sr-qnative"). I would say that you have 2 options:

1. Use the SDK v4.2.0 (which is currently the latest release) on you PC. This version will be the last version to support old modes.
2. Replace your camera module with a newer one (part name is ADTF3175BMLZ) that is configured to work with the new modes.

**Comment by jonny214** [comment]
Thank you so much.
I see. I will get newer module for this.

Best regards,
Jun
